### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by KatrinaHarris23** [cdeitrick/Lolipop#63]
The current version outputs a folder "scripts" that is empty. Previous versions had at least an r script here to allow easy alteration of ggmuller parameters. Would be nice to have that output again.

**Comment by cdeitrick** [comment]
Version 0.9.0 generates an r script for each color scheme generated in the `graphics` folder. There are currently two colorschemes: `lineage` assigns each genotype a shade of color based on the overarching color of the corresponding lineage while `unique` assigns distinct colors to each genotype to make differentiating between genotypes easier. Each colorscheme has its own folder within the `graphics` folder, and each colorscheme folder now contains an r script to generate an unannotated muller plot using the equivalent code using the `ggmuller` package.
